"""Renderer for pyproject.toml output format."""
import tomlkit
from pytest_pw_config_gen.models import PlaywrightConfig


def render(config: PlaywrightConfig) -> str:
    """Render a pyproject.toml [tool.pytest.ini_options] block from a PlaywrightConfig.

    Args:
        config: PlaywrightConfig instance with all settings.

    Returns:
        A string suitable for writing to pyproject.toml (passes tomlkit.loads()).

    Raises:
        RuntimeError: If the rendered TOML is not valid (round-trip check fails).
    """
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by pytest-pw-config-gen — edit freely"))
    doc.add(tomlkit.comment("Re-run the generator to regenerate this file."))
    doc.add(tomlkit.nl())

    # Build [tool.pytest.ini_options] structure
    tool_table = tomlkit.table(is_super_table=True)
    pytest_table = tomlkit.table(is_super_table=True)
    ini_table = tomlkit.table()

    # --- addopts as TOML array of strings ---
    addopts = tomlkit.array()
    for browser in config.browsers:
        addopts.append("--browser")
        addopts.append(browser)
    if config.headed:
        addopts.append("--headed")
    if config.browser_channel is not None:
        addopts.append("--browser-channel")
        addopts.append(config.browser_channel)
    if config.base_url is not None:
        addopts.append("--base-url")
        addopts.append(config.base_url)
    if config.slowmo > 0:
        addopts.append("--slowmo")
        addopts.append(str(config.slowmo))
    addopts.append("--tracing")
    addopts.append(config.tracing)
    addopts.append("--video")
    addopts.append(config.video)
    addopts.append("--screenshot")
    addopts.append(config.screenshot)
    if config.output_dir is not None:
        addopts.append("--output")
        addopts.append(config.output_dir)
    if config.device is not None:
        addopts.append("--device")
        addopts.append(config.device)
    if config.reruns > 0:
        addopts.append("--reruns")
        addopts.append(str(config.reruns))
    if config.workers is not None:
        addopts.append("-n")
        addopts.append(str(config.workers))
    if config.reporter == "html":
        addopts.append("--html=report.html")
    elif config.reporter == "junit":
        addopts.append("--junitxml=report.xml")
    elif config.reporter == "json":
        addopts.append("--json-report")
        addopts.append("--json-report-file=report.json")

    ini_table.add("addopts", addopts)

    # --- Standalone ini options ---
    ini_table.add(tomlkit.comment("seconds; requires pytest-timeout plugin"))
    ini_table.add("timeout", config.timeout)

    testpaths_arr = tomlkit.array()
    for path in config.testpaths:
        testpaths_arr.append(path)
    ini_table.add("testpaths", testpaths_arr)

    if config.markers:
        markers_arr = tomlkit.array()
        for marker in config.markers:
            markers_arr.append(marker)
        ini_table.add("markers", markers_arr)

    pytest_table.add("ini_options", ini_table)
    tool_table.add("pytest", pytest_table)
    doc.add("tool", tool_table)

    result = tomlkit.dumps(doc)

    # Round-trip validation
    try:
        tomlkit.loads(result)
    except Exception as exc:
        raise RuntimeError(
            f"Rendered pyproject.toml failed round-trip validation:\n{result}"
        ) from exc

    return result
