"""Renderer for pytest.ini output format."""
from pytest_pw_config_gen.models import PlaywrightConfig

HEADER = (
    "# Generated by pytest-pw-config-gen — edit freely\n"
    "# Re-run the generator to regenerate this file.\n\n"
)


def render(config: PlaywrightConfig) -> str:
    """Render a pytest.ini file string from a PlaywrightConfig.

    Args:
        config: PlaywrightConfig instance with all settings.

    Returns:
        A string suitable for writing to pytest.ini.
    """
    lines = [HEADER, "[pytest]\n"]

    # --- addopts block (multi-line, each flag on its own indented line) ---
    addopts_lines = []
    for browser in config.browsers:
        addopts_lines.append(f"    --browser {browser}")
    if config.headed:
        addopts_lines.append("    --headed")
    if config.browser_channel is not None:
        addopts_lines.append(f"    --browser-channel {config.browser_channel}")
    if config.base_url is not None:
        addopts_lines.append(f"    --base-url {config.base_url}")
    if config.slowmo > 0:
        addopts_lines.append(f"    --slowmo {config.slowmo}")
    addopts_lines.append(f"    --tracing {config.tracing}")
    addopts_lines.append(f"    --video {config.video}")
    addopts_lines.append(f"    --screenshot {config.screenshot}")
    if config.output_dir is not None:
        addopts_lines.append(f"    --output {config.output_dir}")
    if config.device is not None:
        addopts_lines.append(f'    --device "{config.device}"')
    if config.reruns > 0:
        addopts_lines.append(
            f"    --reruns {config.reruns}  # requires pytest-rerunfailures plugin"
        )
    if config.workers is not None:
        addopts_lines.append(
            f"    -n {config.workers}  # requires pytest-xdist plugin"
        )
    if config.reporter == "html":
        addopts_lines.append("    --html=report.html  # requires pytest-html plugin")
    elif config.reporter == "junit":
        addopts_lines.append("    --junitxml=report.xml")
    elif config.reporter == "json":
        addopts_lines.append(
            "    --json-report --json-report-file=report.json"
            "  # requires pytest-json-report plugin"
        )

    lines.append("addopts =\n")
    for flag_line in addopts_lines:
        lines.append(flag_line + "\n")

    lines.append("\n")

    # --- Standalone ini options ---
    lines.append(
        f"timeout = {config.timeout}  # seconds; requires pytest-timeout plugin\n"
    )

    testpaths_str = " ".join(config.testpaths)
    lines.append(f"testpaths = {testpaths_str}\n")

    if config.markers:
        lines.append("\nmarkers =\n")
        for marker in config.markers:
            lines.append(f"    {marker}\n")

    return "".join(lines)
